import { getGmailAliases } from './server/gmail.js';
import { createQueryString, makeQueryString } from './server/http.js';
import { doGet } from './server/webapp.js';
import {
  getAppData,
  getAvailability,
  getDatabaseInfo,
  getStaffAdminData,
  geocodeD3Schools,
  markSchoolContacted,
  recordAttendance,
  updateRiskFormStatus,
  sendRiskFormLink,
  sendCampaign,
  previewCampaign,
  saveSetting,
  saveAvailabilitySlot,
  saveStaffRecord,
  approveReservation,
  cancelReservation,
  sendReservationReminder,
  installD3AutomationTriggers,
  runD3DailyAutomation,
  runD3SystemCheck,
  submitReservation,
} from './server/fieldTrips.js';

export {
  createQueryString,
  doGet,
  getAppData,
  getAvailability,
  getDatabaseInfo,
  getStaffAdminData,
  geocodeD3Schools,
  getGmailAliases,
  markSchoolContacted,
  recordAttendance,
  previewCampaign,
  sendCampaign,
  sendRiskFormLink,
  updateRiskFormStatus,
  installD3AutomationTriggers,
  makeQueryString,
  runD3DailyAutomation,
  runD3SystemCheck,
  saveSetting,
  saveAvailabilitySlot,
  saveStaffRecord,
  sendReservationReminder,
  approveReservation,
  cancelReservation,
  submitReservation,
};
